/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-11-30 16:04:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sampleCompteProxy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<HTML>\n");
      out.write("<HEAD>\n");
      out.write("<TITLE>Inputs</TITLE>\n");
      out.write("</HEAD>\n");
      out.write("<BODY>\n");
      out.write("<H1>Inputs</H1>\n");
      out.write("\n");

String method = request.getParameter("method");
int methodID = 0;
if (method == null) methodID = -1;

boolean valid = true;

if(methodID != -1) methodID = Integer.parseInt(method);
switch (methodID){ 
case 2:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 5:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<TABLE>\n");
      out.write("<TR>\n");
      out.write("<TD COLSPAN=\"1\" ALIGN=\"LEFT\">endpoint:</TD>\n");
      out.write("<TD ALIGN=\"left\"><INPUT TYPE=\"TEXT\" NAME=\"endpoint8\" SIZE=20></TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 10:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 13:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 16:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<TABLE>\n");
      out.write("<TR>\n");
      out.write("<TD COLSPAN=\"1\" ALIGN=\"LEFT\">depot:</TD>\n");
      out.write("<TD ALIGN=\"left\"><INPUT TYPE=\"TEXT\" NAME=\"depot19\" SIZE=20></TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 21:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<TABLE>\n");
      out.write("<TR>\n");
      out.write("<TD COLSPAN=\"1\" ALIGN=\"LEFT\">retrait:</TD>\n");
      out.write("<TD ALIGN=\"left\"><INPUT TYPE=\"TEXT\" NAME=\"retrait24\" SIZE=20></TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 1111111111:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<TABLE>\n");
      out.write("<TR>\n");
      out.write("<TD COLSPAN=\"1\" ALIGN=\"LEFT\">URLString:</TD>\n");
      out.write("<TD ALIGN=\"left\"><INPUT TYPE=\"TEXT\" NAME=\"url1111111111\" SIZE=20></TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
case 1111111112:
valid = false;

      out.write("\n");
      out.write("<FORM METHOD=\"POST\" ACTION=\"Result.jsp\" TARGET=\"result\">\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"method\" VALUE=\"");
      out.print(org.eclipse.jst.ws.util.JspUtils.markup(method));
      out.write("\">\n");
      out.write("<BR>\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Invoke\">\n");
      out.write("<INPUT TYPE=\"RESET\" VALUE=\"Clear\">\n");
      out.write("</FORM>\n");

break;
}
if (valid) {

      out.write("\n");
      out.write("Select a method to test.\n");

}

      out.write("\n");
      out.write("\n");
      out.write("</BODY>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
